# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1.5-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4
    

    working_directory: ~/crud
  
    - add_ssh_keys:
        fingerprints:
          - "1d:f8:fb:10:97:85:14:d3:f5:3c:9c:cc:a5:73:ff:22"

    steps:     
      #- run: scp -P 22 ~/crud/favicon.png root@13.126.42.54:/var/www/html/circleci            
      #- run: ssh root@13.126.42.54 'cd /var/www/html/circleci/crud/ && git pull origin master'
      #- run: rsync -av --dry-run --update ~/crud/* ubuntu@13.126.42.54:/var/www/html/circleci/crud/
      #- run: rsync -av --update ~/crud/* ubuntu@13.126.42.54:/var/www/html/circleci/crud/
       - run: ssh ubuntu@13.126.42.54 'cd /var/www/html/circleci/crud/ && git pull origin master'

    #deploy:
    #  push_to_server:
    #    branch: master
    #    commands:
    #      - ssh ubuntu@13.126.42.54 'cd /var/www/html/circleci/crud/ && git pull origin master'